language: node_js
node_js:
  - '6'
branches:
  only:
    - master
cache:
  directories:
    - node_modules/
script:
    - npm install
    - npm install jest
    - npm install coveralls
    - npm test
    - npm run coveralls